package com.example.styleadvisor.theme

import androidx.compose.ui.graphics.Color

val BackgroundWarmWhite = Color(0xFFFAF7F5)
val TextDarkMaroon = Color(0xFF3E1E1C)
val TextMuted = Color(0xFF6E5E5C)
val ButtonGradientStart = Color(0xFF4C2123)
val ButtonGradientEnd = Color(0xFF280B07)
val ButtonIconBg = Color(0xFFFFD8DC)
val ButtonIconTint = Color(0xFFFF627C)
val PromoGradientStart = Color(0xFFFFE1E5)
val PromoGradientEnd = Color(0xFFFFC7B5)
val NavIconActiveBg = Color(0xFF3E1E1C)
val NavIconActiveTint = Color(0xFFFFFFFF)
val NavIconInactiveTint = Color(0xFF8D7C79)
val FabBg = Color(0xFFFF657F)
val FabTint = Color(0xFFFFFFFF)
val ScoreHigh = Color(0xFF81C784)
val ScoreMedium = Color(0xFFFFD54F)
val ScoreLow = Color(0xFFE57373)
val CardBackground = Color(0xFFFFFFFF)
val SurfaceVariant = Color(0xFFF3EEED)
val ScoreTextRed = Color(0xFFFF4E6A)
val RedPillBg = Color(0xFFFFEBEE)
val RedPillText = Color(0xFFFF4E6A)
val TabActiveText = Color(0xFFFF4E6A)
val TabInactiveText = Color(0xFF6E5E5C)
val PaletteOlive = Color(0xFF55634A)
val PaletteTan = Color(0xFFDAB37B)
val PaletteWhite = Color(0xFFFFFFFF)
val PaletteBrown = Color(0xFF8D532C)
val PaletteBlack = Color(0xFF1E2125)

// Category Badge Colors
val BadgePurpleBg = Color(0xFFF0E6FA)
val BadgePurpleText = Color(0xFF7B52AB)
val BadgeOrangeBg = Color(0xFFFDE8DE)
val BadgeOrangeText = Color(0xFFB3592D)
val BadgeBlueBg = Color(0xFFE6F3FA)
val BadgeBlueText = Color(0xFF3880B2)
val BadgeGreenBg = Color(0xFFE8F7E8)
val BadgeGreenText = Color(0xFF459A45)
val BadgeYellowBg = Color(0xFFFDF6E1)
val BadgeYellowText = Color(0xFFB08920)
