package com.example.styleadvisor.theme

import androidx.compose.ui.graphics.Color

val BackgroundCoolWhite = Color(0xFFF4F7FC)
val ThemeLightBlue = Color(0xFFE8EFFF)
val PrimaryBlue = Color(0xFF4A7DFF)
val TextNavyBlue = Color(0xFF0F172A)
val TextMuted = Color(0xFF64748B)
val ButtonBlueStart = Color(0xFF2563EB)
val ButtonBlueEnd = Color(0xFF1E40AF)
val ButtonIconBlueBg = Color(0xFFDBEAFE)
val ButtonIconBlueTint = Color(0xFF3B82F6)
val PromoBlueStart = Color(0xFFEFF6FF)
val PromoBlueEnd = Color(0xFFBFDBFE)
val PromoGradientStart = Color(0xFFFFE1E5)
val PromoGradientEnd = Color(0xFFFFC7B5)
val PromoPopStart = Color(0xFF38BDF8) // Bright Sky Blue
val PromoPopEnd = Color(0xFF3B82F6)   // Vibrant Blue
val NavIconActiveBlueBg = Color(0xFF1E3A8A)
val NavIconActiveBlueTint = Color(0xFFFFFFFF)
val NavIconInactiveBlueTint = Color(0xFF94A3B8)
val FabBlueBg = Color(0xFF3B82F6)
val FabTint = Color(0xFFFFFFFF)
val ScoreHigh = Color(0xFF81C784)
val ScoreMedium = Color(0xFFFFD54F)
val ScoreLow = Color(0xFFE57373)
val CardBackground = Color(0xFFFFFFFF)
val SurfaceVariant = Color(0xFFF1F5F9)
val ScoreTextBlue = Color(0xFF2563EB)
val BluePillBg = Color(0xFFDBEAFE)
val BluePillText = Color(0xFF1D4ED8)
val TabActiveBlueText = Color(0xFF2563EB)
val TabInactiveBlueText = Color(0xFF64748B)
val PaletteOlive = Color(0xFF55634A)
val PaletteTan = Color(0xFFDAB37B)
val PaletteWhite = Color(0xFFFFFFFF)
val PaletteBrown = Color(0xFF8D532C)
val PaletteBlack = Color(0xFF1E2125)

// Category Badge Colors
val BadgePurpleBg = Color(0xFFF0E6FA)
val BadgePurpleText = Color(0xFF7B52AB)
val BadgeOrangeBg = Color(0xFFFDE8DE)
val BadgeOrangeText = Color(0xFFB3592D)
val BadgeBlueBg = Color(0xFFE6F3FA)
val BadgeBlueText = Color(0xFF3880B2)
val BadgeGreenBg = Color(0xFFE8F7E8)
val BadgeGreenText = Color(0xFF459A45)
val BadgeYellowBg = Color(0xFFFDF6E1)
val BadgeYellowText = Color(0xFFB08920)
